name: bts_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  health: ^8.1.0
  pedometer: ^4.0.1
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  upgrade: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
